### PR TITLE
Check Sqoop job completion before running.

### PR DESCRIPTION
**Pull request by brianhw**
Also check for the marker file when checking for completeness.

### CODE REVIEW

**Comment by brianhw** [comment]
Unit tests pass, as does test_internal_reporting_database acceptance test.   Other acceptance tests are currently running.

**Review by tobz — APPROVED** [review]
LGTM if tests pass. :shipit:

**Review by HassanJaveed84 — APPROVED** [review]

**Comment by brianhw** [comment]
Addresses both DE-99 and DE-100.

**Comment by brianhw** [comment]
DE-99 had been tested this morning, with the success of the user-activity run.  I have now fixed the code so that DE-100 should also be properly addressed.   And I tested it by running a Sqoop task twice.   First I ran with the Sqoop initialization step removed from job's jenkins configuration so that Sqoop failed to run.  It produced the directory and a _metadata file, but no output.  I then reran with the initialization step properly included, and the sqoop task properly deleted the existing partial data and regenerated complete data.  

Once approved, I'll squash the two commits down into a single one before merging.

**Comment by brianhw** [comment]
Oh, I also reran the job after it ran successfully, and it correctly detected that it had already succeeded. 

Ready for re-review.

**Review by azafty468 — APPROVED** [review]
Looks good!

**Pull request merged**
