### PR TITLE
ENT-1985 Cleanup references to enterprise catalog field, which has been removed

### PR DESCRIPTION
**Pull request by brittneyexline**
Analytics Pipeline Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] If you have a migration please contact data engineering team before merging.
  - [ ] Before merging run full acceptance tests suite and provide URL for the acceptance tests run.
  - [ ] A member of data engineering team has approved the pull request.

### CODE REVIEW

**Review by muhammad-ammar — APPROVED** [review]
Thanks for taking care of this.

**Review by christopappas — APPROVED** [review]
Your changes make sense to me, but I will need to defer to you/someone else to verify this actually works 😬

**Comment by brittneyexline** [comment]
Link to acceptance test run of test_enterprise_enrollments: http://jenkins-ci.analytics.edx.org/view/ad-hoc/job/edx-analytics-pipeline-acceptance-test-manual/1741/console

**Review by pwnage101 — APPROVED** [review]
LGTM, thanks!

**Review by macdiesel — APPROVED** [review]

**Pull request merged**
