### PR TITLE
[BD-19] transition from es1.5 to es7

### PR DESCRIPTION
**Pull request by Golub-Sergey**
Analytics Pipeline Pull Request

**Description:** updates ES lib requirements and interfaces which perform tasks that will put data into ES

**Notes:** [Analytics Pipeline to ES7 edx doc](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1770651728/Analytics+Pipeline+to+ES7).

**Was done:**
 - [x] check code coverage and tests passing;
 - [x] update code base.

**Code coverage:**  74%

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Golub-Sergey! I've created [BLENDED-605](https://openedx.atlassian.net/browse/BLENDED-605) to keep track of it in Jira.   More details are on the [BD-19](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1596162490/BD-19+BD-20+Elasticsearch+Haystack+Upgrades) project page.


When this pull request is ready, tag your edX technical lead.

**Comment by estute** [comment]
In order to run acceptance tests against this, I think we will need to upgrade the test instance of ES we use. I will work with my team to plan for this work.

**Comment by Golub-Sergey** [comment]
> In order to run acceptance tests against this, I think we will need to upgrade the test instance of ES we use. I will work with my team to plan for this work.

@estute  I'm going to write tests on pieces for code which decrease coverage

**Comment by estute** [comment]
I tried to run the acceptance tests tonight, and they failed with the following stacktrace:
```
  File "/usr/local/lib/python2.7.12/lib/python2.7/unittest/case.py", line 320, in run
    self.setUp()
  File "/var/lib/jenkins/jobs/acceptance-es-upgrade/workspace/analytics-tasks/edx/analytics/tasks/tests/acceptance/__init__.py", line 304, in setUp
    self.reset_external_state()
  File "/var/lib/jenkins/jobs/acceptance-es-upgrade/workspace/analytics-tasks/edx/analytics/tasks/tests/acceptance/__init__.py", line 329, in reset_external_state
    self.elasticsearch.reset()
  File "/var/lib/jenkins/jobs/acceptance-es-upgrade/workspace/analytics-tasks/edx/analytics/tasks/tests/acceptance/services/elasticsearch_service.py", line 34, in reset
    response = self._elasticsearch_client.indices.get_aliases(name=self._alias)
'\'IndicesClient\' object has no attribute \'get_aliases
```
I believe the ES API has changed the aliases endpoint. See: https://discuss.elastic.co/t/get-aliases-removed-from-elasticsearch-py-python/76092

**Comment by ashultz0** [comment]
pipeline has been moved on to ES7 since this PR so its work is done

**Comment by openedx-webhooks** [comment]
@Golub-Sergey Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-analytics-pipeline&entry.867055334=https://github.com/openedx/edx-analytics-pipeline/pull/835&entry.1484655318=https://github.com/Golub-Sergey&entry.752974735=2020-09-25+19:04&entry.1917517419=2022-05-19+17:23&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
