### PR TITLE
Support more customization via environment variables

### PR DESCRIPTION
**Pull request by mulby**
Provides the following features:
1. Allow AWS region used by the dynamic inventory script (ec2.py) to be configured via an environment variable instead of the hardcoded value in ec2.ini
2. Allow the acceptance tests to read some configuration settings from environment variables as well. This allows us to use a static configuration file for most acceptance tests variables and use Jenkins parameters to override a few critical ones.
3. Fix the answer distribution test so that it uses the configured manifest class if it's provided.

Reviewers:
- [x] @brianhw
- [ ] @HassanJaveed84 

FYI: @itsjeyd 

TODO:
- [x] Run acceptance tests on jenkins-ci and locally

### CODE REVIEW

**Comment by brianhw** [comment]
LGTM.  I'll try running this against AcceptanceTest450.

**Comment by brianhw** [comment]
Actually, can you also rebase this one as well?

**Comment by mulby** [comment]
rebased

**Comment by brianhw** [comment]
LGTM.  :+1:

**Comment by mulby** [comment]
The test that failed was due to a pip install issue.

**Pull request merged**
