### PR TITLE
Removed all BigQuery related code.

### PR DESCRIPTION
**Pull request by HassanJaveed84**
Analytics Pipeline Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] If you have a migration please contact data engineering team before merging.
  - [ ] Before merging run full acceptance tests suite and provide URL for the acceptance tests run.
  - [ ] A member of data engineering team has approved the pull request.

### CODE REVIEW

**Review by pwnage101 — APPROVED** [review]

**Review by brianhw — APPROVED** [review]
LGTM.   👍

**Comment by HassanJaveed84** [comment]
Additional A/C: 
Address feedback noted here: https://github.com/edx/edx-analytics-pipeline/pull/824/files#r452311767

**Review by macdiesel — APPROVED** [review]

**Comment by pwnage101** [comment]
> Additional A/C:
> Address feedback noted here: https://github.com/edx/edx-analytics-pipeline/pull/824/files#r452311767

I'm intentionally ignoring this code cleanliness improvement as we're deprecating this codebase soon anyway.

**Comment by pwnage101** [comment]
I'm giving up on this because I can't get isort to pass.

**Pull request closed without merging**
