### PR TITLE
Add tool for performing curation.

### PR DESCRIPTION
**Pull request by brianhw**
This command-line tool generates curated synthetic enrollment event files from log files created separately by enrollment validation runs.

These event files are in a format where they can be directly added to the pipeline tasks' eventlog source directories.

@mulby @jab5569

### CODE REVIEW

**Comment by brianhw** [comment]
Note that this uses the s3util functionality, so it's branched off of that.  Once that makes it to master, this can be rebased.

**Comment by johnalbaker** [comment]
@brianhw what was the genesis for this addition? I'm just wondering how / when we'd use it. Is it a replacement for synthetic event creation?

**Comment by brianhw** [comment]
It is a replacement for how I have been doing synthetic event creation, which has involved setting up directories, running my personal s3_util tool, running a bash script to grep over files, and then manually comparing the results.  This automates all that in a way that someone else could perform the same operations, both here at edX and at other installations.

**Comment by brianhw** [comment]
@mulby @HassanJaveed84 I've added some doc to this, as well as the statistics that make it more useful.   I would like to merge this at some point.  (After thumbs, I'll squash.)

**Comment by brianhw** [comment]
I suspect that this will at least require adding a hostname argument to s3_connect() in s3util.py.  Or using ScalableS3Client.s3 instead.  But it still won't work with assumed roles.

**Pull request closed without merging**
