### PR TITLE
Fix lock contention on the MySQL marker table

### PR DESCRIPTION
**Pull request by mulby**
Fixes: https://openedx.atlassian.net/browse/AN-5429

Note this is a fix for the release branch, I'll make a separate PR for fixing this on master.

@brianhw @jab5569

### CODE REVIEW

**Comment by johnalbaker** [comment]
@mulby  I'm assuming you'll be submitting a separate PR to have each job insert into the marker table..?

Otherwise :+1:  LGTM.

**Comment by mulby** [comment]
@jab5569 all jobs already make use of the marker table, so no further changes should be necessary

**Comment by brianhw** [comment]
Makes sense.  LGTM. :+1:

**Comment by brianhw** [comment]
And it's a small and reasonable change to submit back to Luigi at some point.  Though I recall we have some issue with upgrading Luigi anyway because newer versions won't run on EMR.

**Pull request closed without merging**
