### PR TITLE
Fix blacklist acceptance test

### PR DESCRIPTION
**Pull request by mulby**
This isn't quite ready, but it's close. I just need to modify the acceptance test to use a custom generated blacklist either by supporting overriding the path at the command line or by overriding the path in the config file that is used by the acceptance test.

@brianhw @jbau

### CODE REVIEW

**Comment by mulby** [comment]
@jbau @brianhw this is ready for review now, the acceptance test passes

**Comment by brianhw** [comment]
LGTM.  :+1:

**Comment by mulby** [comment]
Full acceptance tests passed:

http://jenkins-ci.analytics.edx.org/view/ad-hoc/job/edx-analytics-pipeline-acceptance-test-manual/63/

**Comment by jbau** [comment]
Thanks for fixing

**Pull request merged**
