### PR TITLE
Define s3util command-line tool.

### PR DESCRIPTION
**Pull request by brianhw**
@mulby @jab5569 Finally creating a PR for this.

### CODE REVIEW

**Comment by johnalbaker** [comment]
:+1:

**Comment by mulby** [comment]
nit: I would prefer this was moved to the launchers package where we put the other main entry points

other than that :+1:

**Comment by brianhw** [comment]
Rather than figuring out a different place to put utilities, I'm fine for now with putting them in launchers.

**Comment by mulby** [comment]
k, seems reasonable to me. :+1:

**Pull request merged**
