### PR TITLE
Modify EventLogSelectionTask to accept multiple values for source parameter.

### PR DESCRIPTION
**Pull request by brianhw**
Values in config files may be specified on separate lines.  E.g.:

``` code
  [event-logs]
  source = s3://fake/input/
           s3://fake/input2/
```

### CODE REVIEW

**Comment by brianhw** [comment]
@mulby This also passes acceptance tests.

**Comment by mulby** [comment]
Do we need to update test.cfg as well?

And tests/acceptance/**init**.py maybe?

**Comment by mulby** [comment]
Also, given the validation needed for this, we may want to bundle in the config change to the subdirectory of the tracking log bucket instead of the root.

**Comment by brianhw** [comment]
Test.cfg is already updated as part of this PR, and testing of it is included.  But I like the idea of adding a second source directory to tests/acceptance/init.py, and using that for putting the synthetic events into for acceptance tests.  I think we're going to want to add such events to most if not all tests.  (Even exports, to make sure they are _not_ included.)

**Comment by mulby** [comment]
:+1:

**Pull request merged**
