### PR TITLE
Send unit testing coverage stats to datadog.

### PR DESCRIPTION
**Pull request by benpatterson**
@jzoldak @mulby @brianhw @jab5569

This is currently being done on Jenkins...we'd replace the in-job bash with this (for the most part--ignoring the venv setup).

### CODE REVIEW

**Comment by brianhw** [comment]
Looks reasonable.  But this is still tied to Jenkins, in that it piggy-backs on the existing coverage.xml output.

**Comment by benpatterson** [comment]
Wise as usual, @brianhw. Although we don't remove Jenkins dependency entirely, it is an incremental step away, by putting this into a script file. 

That way, if we, say, put unit testing on Travis, then we'd just use this script as a post-build task (when coverage.xml is available.)

**Comment by brianhw** [comment]
Okay.  :+1:

**Comment by benpatterson** [comment]
@mulby @jab5569 could one of you fellas give a pass on this change as well?

**Comment by mulby** [comment]
:+1:

**Pull request merged**
