### PR TITLE
Change override behavior to merge override.cfg into client.cfg

### PR DESCRIPTION
**Pull request by jbau**
@mulby Here's the tool we talked about that merges .cfg files.
I tested that it works fine in our env.

The problem is, my task machines are still not reading the overrides...

### CODE REVIEW

**Comment by sarina** [comment]
@mulby ping

**Comment by mulby** [comment]
@jbau did you figure out why the change wasn't getting picked up on the
slave node?

**Comment by jbau** [comment]
Haven't yet.  (Got busy with other stuff)  But will do it tomorrow.

**Comment by jbau** [comment]
@mulby and I found that client.cfg isn't getting shipped around either.  I still think this particular PR is worth keeping open, but more needs to be done around it.

**Comment by mulby** [comment]
@jbau - Happy to leave it open as long as you need. Let me know if/when you want me to look at it again.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jbau! I've created [OSPR-391](https://openedx.atlassian.net/browse/OSPR-391) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by sarina** [comment]
@jbau is this work that someone is going to pick up once you leave Stanford?

If not, @mulby is this work you want to keep around for your team to pick up, or should we close it?

**Pull request closed without merging**
