### PR TITLE
Fixed unfulfilled dependency issue.

### PR DESCRIPTION
**Pull request by HassanJaveed84**
@mulby @brianhw 
This should fix the unfulfilled dependency issue.

### CODE REVIEW

**Comment by mulby** [comment]
:exclamation: Great work

can you incorporate this change with it: https://github.com/edx/edx-analytics-pipeline/pull/251

**Comment by HassanJaveed84** [comment]
Done.

**Comment by mulby** [comment]
:+1:

**Comment by brianhw** [comment]
LGTM. 👍

**Comment by HassanJaveed84** [comment]
Should I merge this as is or squash before ?

**Comment by mulby** [comment]
Either way is fine. You can merge as is.

**Pull request merged**
