### PR TITLE
Switch to fork of luigi using v1.0.17

### PR DESCRIPTION
**Pull request by brianhw**
@mulby @rocha  Upgrading from 1.0.16 to v1.0.17, in preparation for making changes to Luigi fork.

### CODE REVIEW

**Comment by mulby** [comment]
:+1:

**Comment by rocha** [comment]
My only suggestion is to use a special version for the luigi fork. I suggest something like 1.0.17-fork-edx-1. On the luigi fork it is necessary to change `setup.py` to use that version number, and it also helps to tag the corresponding fork release.

The main advantage is that it makes easier to find pip problems, since just doing a `pip list` will show you if the right version got installed or not.

**Comment by brianhw** [comment]
@rocha I plan to do that when I actually make a change to Luigi.

**Comment by rocha** [comment]
cool :rocket:

**Pull request merged**
