### PR TITLE
Compute historical user activity

### PR DESCRIPTION
**Pull request by mulby**
I think this is the bare minimum changeset that will allow us to see historical user activity.

### CODE REVIEW

**Comment by mulby** [comment]
obviously needs additional unit tests, and might require the acceptance test to be modified as well

**Comment by brianhw** [comment]
Yup, but the interval math logic looks good to me.

**Comment by mulby** [comment]
@brianhw this is ready for review again

**Comment by brianhw** [comment]
LGTM.  :+1:

**Pull request merged**
