### PR TITLE
SE-1032 Adds option to store anonymous user events in module_engagement hive table (ironwood.master)

### PR DESCRIPTION
**Pull request by pomegranited**
Cherry-picked from https://github.com/edx/edx-analytics-pipeline/pull/734

We have tested this branch on our client who's running the Ironwood Analytics Pipeline, and it's working smoothly there.

**Reviewers**

- [ ] @brianhw ?

CC @nedbat 

Analytics Pipeline Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] If you have a migration please contact data engineering team before merging.
  - [ ] Before merging run full acceptance tests suite and provide URL for the acceptance tests run.
  - [ ] A member of data engineering team has approved the pull request.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! I've created [OSPR-3756](https://openedx.atlassian.net/browse/OSPR-3756) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Review by brianhw — APPROVED** [review]
LGTM.   👍

**Comment by brianhw** [comment]
@nedbat Any reason I shouldn't just merge this?

**Comment by nedbat** [comment]
No reason not to!

**Comment by natabene** [comment]
@pomegranited Thank you for your contribution. 
@brianhw Do you want to merge now or do you want to have a second reviewer from edX look at it first? Up to you

**Comment by openedx-webhooks** [comment]
@pomegranited 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-pipeline&entry.867055334=https://github.com/edx/edx-analytics-pipeline/pull/749&entry.1484655318=https://github.com/pomegranited&entry.752974735=2019-07-23+02:01&entry.1917517419=2019-07-23+17:59&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by pomegranited** [comment]
Thank you @brianhw and @nedbat and @natabene !

**Pull request merged**
