### PR TITLE
Change how metric ranges are specified.

### PR DESCRIPTION
**Pull request by HassanJaveed84**
@mulby @brianhw this is ready for review.

I'm still thinking on how to better specify the different range values, I'm open to suggestions.

### CODE REVIEW

**Comment by mulby** [comment]
The more I think about this, I'm now concerned that it's impossible for a value of "inf" to be anything other than "normal". Could it ever be categorized as "high"?

@dsjen @dan-f @brianhw @shnayder  - we are codifying our discussion of the metric ranges here and I'm still not convinced we have a solution that does what we want. Feel free to weigh in.

To make things easier to reason about let's say the percentiles are actually 10 and 90 (easier for in your head math).

Now if I had an input that was `[2]*8 + [float('inf')]*2`. This would mean that 80% of the learners had a ratio of 2 and the other 20% had an undefined value. In this case the "inf" value is really in the "high" bucket, however, our current logic would just make the normal range `2 <= value < inf` and not define a "high" range. In this case I guess I would actually expect:

normal: `2 <= value < inf`
high: `value == inf`

It would only land in the "high" bucket if it was actually equal to float('inf').

More context here: https://openedx.atlassian.net/browse/AN-6897 (note that I made this ticket public)

**Comment by mulby** [comment]
@HassanJaveed84 to provide more context, these ranges are used to identify users who are outside of the "normal" range for a particular metric, such as the ratio of problem attempts to problems completed correctly.

It is possible for users to perform 10 attempts and not get any problems correct, which can result in these float('inf') values (10/0).

**Comment by mulby** [comment]
More interesting test cases (assuming 10th, 90th):

input: `[1]*10 + [float('inf')]`
In this case the users with the value of `1` should be "normal" and the user with the value of `float('inf')` should be "high". Not sure how to construct the ranges so that would be the case.

**Comment by shnayder** [comment]
Product note: it'd be ok by me to special case 'inf' and compute percentiles of the rest. The point is to highlight the top and bottom ranges -- the exact formula doesn't matter. We'll likely want to tweak parameters once we get some feedback anyway.

**Pull request closed without merging**
