### PR TITLE
WIP: Ingest invoice transactions

### PR DESCRIPTION
**Pull request by itsjeyd**
This PR adds new tasks for ingesting invoice transactions from Otto.

cf. [WL-363](https://openedx.atlassian.net/browse/WL-363)

**Approach**
1. Import relevant tables from `ecommerce` DB (`invoice_invoice`).
2. Use a Hive query to create full transaction records for the data from the previous step.
3. Feed transaction records to the reconciliation task.

**Reviewers**:
- [x] @e-kolpakov 
- [ ] @brianhw 
- [ ] @mjfrey 

**Author notes and concerns**
- Some Otto invoices are not linked to corresponding orders during the reconciliation step. This happens when the corresponding order is linked to an entry in the `catalogue_product` table that is `standalone` and doesn't have a "parent" (`parent_id` set to `NULL`). These types of orders don't make it into the `order` table when running `OrderTableTask`; the `insert_query` of `OrderTableTask` filters them out. This is existing behavior.
### Test instructions

**Basic requirements**
- Set up an [analytics devstack](http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/installation/analytics/index.html). Ensure that the Vagrantfile contains the mount points and port added in [this commit](https://github.com/edx/configuration/pull/2878/files#diff-549ab5b641d2bf3723816a8e3b8c9696).
- Make sure `staff` has superuser privileges and can access Django admin.

**Setting up Otto**
1. Start Otto via:
   
   ``` sh
   sudo su ecommerce
   make serve
   ```
   
   You might have to [update your Django settings](https://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/ecommerce/install_ecommerce.html#update-django-settings) beforehand.
2. Go to http://localhost:8002/ and log in as `staff@example.com`.
3. Follow steps [6.2](https://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/ecommerce/config_partner_site.html) and [6.3](https://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/ecommerce/manage_assets.html) from the official documentation.

**Generating Otto data**
1. Login to Studio as `staff@example.com`, create an empty course and call it "Otto Paid". After creation, edit the course's schedule so its start date is in the past.
2. Follow step [6.4](https://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/ecommerce/create_products.html) from the official documentation to create a "Product" for the course added in the previous step.
   - Course ID: Enter `course-v1:...` ID for course added in previous step
   - Course Name: "Otto Paid"
   - Course Type: Verified
   - Course Seats ⟶ Verified Price: 20
   - Course Seats ⟶ Upgrade deadline: 01/01/2017, 01:00 AM
   - Verification Deadline: 01/01/2017, 01:00 AM
   - Include Honor Seat: Yes
3. Go to http://localhost:8002/coupons/.
4. Click "Create Coupon", fill in the fields as shown in the screenshot below, and click "Create Coupon".
   otto-enrollment-codes-opr
5. (Optional) Go to http://localhost:8002/admin/invoice/invoice/1 and change the "State" of the newly created invoice to "Paid".

**Running tasks**

On your host computer, starting from the `analyticstack` directory:

``` sh
cd ../edx-analytics-pipeline
source venv/bin/activate
export WHEEL_URL=http://edx-wheelhouse.s3-website-us-east-1.amazonaws.com/Ubuntu/precise
# Make sure to replace /path/to/analyticstack/ with appropriate value in the following command:
remote-task --vagrant-path /path/to/analyticstack --remote-name devstack --override-config ${PWD}/config/devstack.cfg --wheel-url $WHEEL_URL --branch tim/ingest-invoice-transactions --wait ReconciledOrderTransactionTableTask --local-scheduler --import-date $(date +%Y-%m-%d -d "today")
```

**Checking results**

On the analytics devstack, as `vagrant` user:

``` sh
sudo su hadoop
hive
select * from invoice_invoice;
select * from invoice;
select * from reconciled_order_transactions;
```

The contents of the first table should be identical to the contents of the corresponding table in the `ecommerce` DB. The `invoice` table should contain transaction records for the data from the first table. The last table should contain a single record for each invoice transaction (but will also contain other entries).

**Deleting results**

You can use the following commands to delete the data that is created when running the commands under "Running tasks" above:

``` sh
sudo su hadoop
hive --service cli -e "DROP TABLE auth_user; DROP TABLE catalogue_product; DROP TABLE catalogue_productattribute; DROP TABLE catalogue_productattributevalue; DROP TABLE catalogue_productclass; DROP TABLE ecommerce_user; DROP TABLE invoice; DROP TABLE invoice_invoice; DROP TABLE order; DROP TABLE order_line; DROP TABLE order_order; DROP TABLE order_orderdiscount; DROP TABLE partner_partner; DROP TABLE reconciled_order_transactions; DROP TABLE refund_refundline; DROP TABLE shoppingcart_certificateitem; DROP TABLE shoppingcart_coupon; DROP TABLE shoppingcart_couponredemption; DROP TABLE shoppingcart_courseregcodeitem; DROP TABLE shoppingcart_donation; DROP TABLE shoppingcart_order; DROP TABLE shoppingcart_orderitem; DROP TABLE shoppingcart_paidcourseregistration; DROP TABLE voucher_couponvouchers; DROP TABLE voucher_couponvouchers_vouchers;"
hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/auth_user; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/catalogue_product; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/catalogue_productattribute; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/catalogue_productattributevalue; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/catalogue_productclass; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/ecommerce_user; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/invoice; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/invoice_invoice; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/order; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/order_line; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/order_order; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/order_orderdiscount; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/partner_partner; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/reconciled_order_transactions; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/refund_refundline; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/shoppingcart_certificateitem; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/shoppingcart_coupon; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/shoppingcart_couponredemption; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/shoppingcart_courseregcodeitem; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/shoppingcart_donation; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/shoppingcart_order; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/shoppingcart_orderitem; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/shoppingcart_paidcourseregistration; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/voucher_couponvouchers; hdfs dfs -rm -r /edx-analytics-pipeline/warehouse/voucher_couponvouchers_vouchers
```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @itsjeyd! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=223&repo=edx%2Fedx-analytics-pipeline

**Comment by brianhw** [comment]
@itsjeyd Sorry for making a premature comment, but I'm confused by the current ShoppingCartInvoiceTransactionsByDayTask implementation.  I'm not sure that it makes as much sense here to separate out the invoice data into separate days as it is with the other transactions that are being pulled incrementally.  These invoices are being dumped from a database in the same way that orders are, so we should probably just output a single file in a "partition" with today's date.  And since the raw data is loaded into Hive already, this task that adds the columns needed to be a "transaction" should probably just be a Hive query itself.  And if using Hive, it should be possible to join with other Hive tables if that helps with finding good values to use for payment_ref_id and the like.

**Comment by brianhw** [comment]
@itsjeyd As I think about this more, because the invoices are not loaded incrementally, I think they should be written out to a separate location in the warehouse, and not lumped with payments (which are incremental).  So I propose that the Reconcile task depend on _three_ other tasks:  Orders, Payments, and Invoices.  But that the three inputs continue to have two formats:  Orders produce orderitems and Payments and Invoices produce transactions.  So the Invoices task would produce output similar to the way that Orders does, but in a format of a transaction.

**Comment by itsjeyd** [comment]
@brianhw No worries at all, I appreciate the feedback. [This commit](https://github.com/edx/edx-analytics-pipeline/pull/223/commits/42a7bc95ffe6170b89309fd064f45689460c93ea) implements the approach you suggested, please let me know if it's what you had in mind. (I didn't remove the code for the previous approach yet to make the diff easier to read; will do that once you confirm the new approach.)

**Comment by brianhw** [comment]
Yes, that looks like a great direction.  I know that orders does a single task and performs a Union, but I think that breaking it up into two separate tasks is actually cleaner.

This seems to provide a reasonable mechanism for getting invoices in as transactions.  I have further questions about how to get useful payment_ref_id values for shoppingcart invoices, and what state the invoices should be in to be included, but I'll take those off-line.

**Comment by e-kolpakov** [comment]
@itsjeyd :+1:

**Comment by itsjeyd** [comment]
@brianhw @mjfrey This is ready for you to have a look. I listed relevant commits in the PR description, but to view the entire changeset at once you can also have a look at the fake [PR](https://github.com/open-craft/edx-analytics-pipeline/pull/3) targetting the branch that this PR is based on. The acceptance test data will need to be adjusted once @smarnach [finalizes the acceptance test data](https://github.com/edx/edx-analytics-pipeline/pull/220#issuecomment-206450177) for his PR (https://github.com/edx/edx-analytics-pipeline/pull/220).

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @itsjeyd! I've created [OSPR-2124](https://openedx.atlassian.net/browse/OSPR-2124) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-analytics-pipeline/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@itsjeyd The bot found an old PR... Do you want to keep this open, or should we close it?

**Comment by itsjeyd** [comment]
@nedbat Thanks for checking in! The ticket that corresponds to this PR was closed as ["no longer relevant"](https://openedx.atlassian.net/browse/WL-363?focusedCommentId=245086&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-245086) a while back, so we can close this PR. I'm going to go ahead and do that now.

**Comment by openedx-webhooks** [comment]
@itsjeyd Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-pipeline&entry.867055334=https://github.com/edx/edx-analytics-pipeline/pull/223&entry.1484655318=https://github.com/itsjeyd&entry.752974735=2016-03-25+18:59&entry.1917517419=2018-01-15+09:15&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
