### PR TITLE
Updated opaque-keys version

### PR DESCRIPTION
**Pull request by HassanJaveed84**
@brianhw @mulby

### CODE REVIEW

**Comment by brianhw** [comment]
LGTM. :+1:

**Comment by HassanJaveed84** [comment]
@brianhw just a heads up, the previous tag referred to a commit from Oct '14.

**Comment by mulby** [comment]
:+1:

**Comment by brianhw** [comment]
Good to know.  If it passes unit and acceptance tests, however, I think it's good to go.

**Comment by brianhw** [comment]
Did you run the unit and acceptance tests first?  Looks like the unit tests don't even pass.

**Comment by brianhw** [comment]
It looks like there is another fix needed in Opaque Keys to deal with this.

**Pull request merged**
