### PR TITLE
Strips delimiters from the 10 auth_userprofile fields appended to ModuleEngagementRosterRecord

### PR DESCRIPTION
**Pull request by pomegranited**
Strips tabs and newlines before adding the following `auth_userprofile` fields to the `ModuleEngagementRosterRecord`
- user_id
- language
- location
- year_of_birth
- level_of_education
- gender
- mailing_address
- city
- country
- goals

**Discussions**: This change was reverted by #292.  See #291 for discussion.

**Partner information**: 3rd party-hosted open edX instance

**Testing Setup**:

<details>
<summary>

Testing setup isn't as extensive as it used to be, thanks to Gabe's updated instructions :smile:</summary>

1. Set up analyticstack according to [edx instructions](http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/installation/analytics/install_analytics.html).  
   Note that these have changed, and you don't need to run `remote-task` to create the `/var/lib/analyticstack` directory anymore.  You can just run everything from the vagrant instance's `/edx/apps/analytics_pipeline/analytics_pipeline`, which maps to your host machine's `edx-analytics-pipeline` dir.
2. Create LMS user and tracking data:
   1. [Run Studio](http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/installation/analytics/start_analytics.html#starting-the-open-edx-lms)
   2. Create and publish a course in Studio, with one or more Problem Units.
   3. [Run LMS](http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/installation/analytics/start_analytics.html#starting-the-open-edx-lms)
   4. Register 2 or 3 student accounts, and enrol them in your course.  To test the whitespace stripping in this change, ensure that some of the above fields (e.g. `goals`, `city`, `country`) contain tabs and newlines.
   5. Have them attempt some problems.  To test all the different data permutations:
      - perform multiple attempts
      - make some students get the problems correct, and some incorrect.
   6. Check that `/edx/var/log/tracking/tracking.log` is receiving these events.
   7. Check that hdfs is receiving the updated tracking logs (cron'd every 1 min),
      by browsing to the [hdfs explorer](http://localhost:50070/explorer.html), and navigating to the `data` folder.
3. Set up analytics ElasticSearch.  
   
   _NB_ The analyticstack already runs ES v0.90 for the LMS/Forum, but the analytics API and pipeline require ES v1.5.   There are [other possible approaches](https://openedx.atlassian.net/wiki/display/AN/Learner+Analytics#LearnerAnalytics-ElasticSearch), but here I decided to run two ES instances on vagrant, on different ports, using the [Analytics Data API instructions](https://github.com/edx/edx-analytics-data-api):
   
   ```
   vagrant ssh
   sudo su analytics_api
   source /edx/app/analytics_api/venvs/analytics_api/bin/activate
   # Runs ES on port 9223 by default.
   ~/analytics_api$ make test.install_elasticsearch
   ~/analytics_api$ make test.run_elasticsearch
   ```
4. Checkout this PR's branch under `/edx/app/analytics_pipeline/analytics_pipeline`.
5. Initialize the virtualenv and run `make bootstrap` to install the updated tasks.
6. Provide an `override.cfg` configuration file to use when running tasks.
   
   Here, we point the analytics pipeline to the ES instance created in step 3,
   and allow empty module-engagement data inserts, to account for our sparse tracking data.
   
   ```
   cp config/devstack.cfg override.cfg
   vim override.cfg # make changes below
   diff -u config/devstack.cfg  override.cfg
   --- config/devstack.cfg 2016-07-27 09:30:36.422732328 +0000
   +++ override.cfg    2016-07-27 11:54:26.860951553 +0000
   @@ -78,9 +78,10 @@  
   dropoff_threshold = 0.05
   
   [elasticsearch]
   -# Point to the vagrant host's port 9201 where we assume elasticsearch is running
   -host = http://172.17.0.1:9201/
   +# Point to the analytics data API's test elasticsearch cluster on port 9233
   +host = http://127.0.0.1:9223/
   
   [module-engagement]
   alias = roster
   number_of_shards = 5
   +# Allow empty inserts, since our tracking data is sparse
   +allow_empty_insert = true
   ```
7. From `/edx/app/analytics_pipeline/analytics_pipeline`, run the `ImportEnrollmentsIntoMysql` task, to import enrollment records required by the module engagement task.
   Ensure that the `--interval` parameter is set to cover the days present in your tracking log.
   
   ```
   TOMORROW=`date --date="tomorrow" +%Y-%m-%d`
   INTERVAL="2016-07-01-$TOMORROW"
   launch-task ImportEnrollmentsIntoMysql --interval $INTERVAL --local-scheduler
   ```
8. Run the `ModuleEngagementWorkflowTask` to import learner profile and engagement data into ElasticSearch.
   
   ```
   TOMORROW=`date --date="tomorrow" +%Y-%m-%d`
   launch-task ModuleEngagementWorkflowTask --date $TOMORROW --local-scheduler --n-reduce-tasks 2 --remote-log-level DEBUG
   ```
9. Run the Analytics Data API:
   1. Adjust the settings to point to our ES instance and index/alias:
      
      ```
      vagrant ssh
      sudo cp /edx/etc/analytics_api.yml /edx/etc/analytics_api.yml.orig
      sudo vim /edx/etc/analytics_api.yml  # apply changes below
      diff -u analytics_api.yml.orig analytics_api.yml
      --- analytics_api.yml.orig  2016-07-27 12:00:23.363453820 +0000
      +++ analytics_api.yml   2016-07-27 12:00:31.278970508 +0000
      @@ -24,8 +24,8 @@
      ELASTICSEARCH_AWS_SECRET_ACCESS_KEY: null
      ELASTICSEARCH_CONNECTION_CLASS: null
      ELASTICSEARCH_CONNECTION_DEFAULT_REGION: us-east-1
      -ELASTICSEARCH_LEARNERS_HOST: localhost
      -ELASTICSEARCH_LEARNERS_INDEX: roster_1_2
      +ELASTICSEARCH_LEARNERS_HOST: localhost:9223    # matches ES host:port from step N
      +ELASTICSEARCH_LEARNERS_INDEX: roster           # matches alias of roster index used by pipeline.
      ELASTICSEARCH_LEARNERS_UPDATE_INDEX: index_updates
      EMAIL_HOST: localhost
      EMAIL_HOST_PASSWORD: mail_password
      ```
   2. [Create an API key for an existing LMS staff user](http://edx-data-analytics-api.readthedocs.io/en/latest/authentication.html#edx-data-analytics-api-authentication), e.g.
      
      ```
      sudo su analytics_api
      source /edx/app/analytics_api/venvs/analytics_api/bin/activate
      cd /edx/app/analytics_api/analytics_api
      ./manage.py set_api_key staff token  # 'token' becomes an API key
      ```
   3. [Run the Analytics Data API server](http://edx-data-analytics-api.readthedocs.io/en/latest/setup.html#run-the-server):
   
   ```
   ./manage.py runserver 0.0.0.0:8100 --insecure
   ```
   
   </details>

**Testing Instructions**:
1. View the analytics pipeline data via the Analytics API using the swagger.io UI:
   1. Visit [the swagger.io UI](http://localhost:8100)
   2. Enter your token in the "API Key" field, and click Explore
   3. Try out GET /authenticated request to ensure 200 response returned
   4. Try out GET /api/v0/learners/ request, with your `course_id` filled in (e.g. `course-v1:edX+DemoX+Demo_Course`)
   5. Note that the new fields are included in the response.
2. Or by using `curl`:
   
   ```
   API_TOKEN="<your API token>"
   COURSE_ID="<your URL-encoded course_id>"  #  e.g. "course-v1%3AedX%2BDemoX%2BDemo_Course"
   
   # View JSON description of the API call (note "text/csv" in the "renders" list):
   curl -X OPTIONS \
     --header "Authorization: Token $API_TOKEN" \
     "http://localhost:8100/api/v0/learners/?course_id=$COURSE_ID"
   
   # View CSV learner profile data, including response headers:
   curl -X GET --include
   --header "Authorization: Token $API_TOKEN" \
   --header "Accept: text/csv" \
   "http://localhost:8100/api/v0/learners/?course_id=$COURSE_ID"
   
   # View paginated CSV learner profile data (e.g. one learner per page), including response headers:
   # Note the "Link" header, which is added if there is >1 page of data.
   curl -X GET --include \
   --header "Authorization: Token $API_TOKEN" \
   --header "Accept: text/csv" \
   "http://localhost:8100/api/v0/learners/?course_id=$COURSE_ID&page_size=1"
   ```
3. Run unit tests (also installs test dependencies):
   
   ```
   vagrant ssh
   cd /edx/apps/analytics_pipeline/analytics_pipeline
   source ../venvs/analytics_pipeline/bin/activate
   export WHEEL_URL=http://edx-wheelhouse.s3-website-us-east-1.amazonaws.com/Ubuntu/precise
   export WHEEL_PYVER=python2.7
   
   make coverage
   ```
4. Run updated acceptance test:
   
   ```
   make test-acceptance-local ONLY_TESTS=edx.analytics.tasks.tests.acceptance.test_module_engagement
   ```

</details>

**Author Notes and Concerns**:
1. The `auth_userprofile.language` field doesn't seem to be populated by the Accounts page anymore; instead it feeds a one-to-many relationship with `student_languageproficiency`.  Will need to discuss with the client whether this field is required, and if so, import the `student_languageproficiency` into hive and add a `JOIN` to the roster query.
2. The `auth_userprofile.location` field doesn't seem to be populated by the Accounts page anymore either.  It may be deprecated; will discuss with client.

**Reviewers**
- [ ] @haikuginger
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fedx-analytics-pipeline&number=294

**Comment by haikuginger** [comment]
:+1:
- [x] I tested this: I recreated the environment from #272 and included users with the requisite delimiters in the relevant fields. When viewing in ES and via the Analytics API, those values were converted to single spaces.
- [x] I read through the code
- [x] ~~Includes documentation~~ No documentation necessary

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! I've created [OSPR-1472](https://openedx.atlassian.net/browse/OSPR-1472) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-analytics-pipeline/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by pomegranited** [comment]
@mulby , @brianhw This PR is ready for your review.

**Comment by brianhw** [comment]
This looks good!  But just so I understand the problem:  I know that Sqoop exports of auth_userprofile will preserve tab characters because we don't use tabs as field delimiters (we use ^A).  But Sqoop does use newlines as record delimiters, so it should have replaced newlines with spaces.  But whenever we are creating tab-delimited data from non-tab-delimited data, we have to strip the tabs.  

I'm okay with stripping the \n and \r as well, but we don't really think that's an issue, do we?

This is also not the only place where we might want to do this in future.  At that time, we'll have a better idea of how to generalize this.

**Review by brianhw — APPROVED** [review]
I thought I would get prompted to approve, but here it is:  👍

**Comment by pomegranited** [comment]
Thanks for your review, @brianhw !  

I had reused the [existing regex already in place for the `name` field](https://github.com/edx/edx-analytics-pipeline/pull/294/files#diff-1849e69e88e5e3d5e08cfe1c61b885a4L1047), both to ensure I didn't break that field, and because all the escaping was already worked out :)  But thanks for noting that it's overkill; something to remember if this gets refactored at some point.

@mulby Do I need your approval too, or is this ok to squash and merge?

**Review by mulby — APPROVED** [review]
It looks good, however, I'd like to run acceptance tests and a quick regression test using our production data before merging into master.

**Comment by mulby** [comment]
Believe it or not, I uncovered yet another issue that probably only appears in the production data. The fields in auth_userprofile are "longtext" in MySQL. This can result in _very_ long text strings in the database that elasticsearch will interpret as one "term" (if they don't contain spaces). Apparently elasticsearch has an upper limit on what it will store:

IllegalArgumentException[Document contains at least one immense term in field="mailing_address" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms. (redacted stuff) original message: bytes can be at most 32766 in length; got 67210]; nested: MaxBytesLengthExceededException[bytes can be at most 32766 in length; got 67210]

In theory this could happen in any of the following fields: meta, mailing_address, goals, and city

**Comment by pomegranited** [comment]
@mulby Oo, thanks for checking that!

5983cce truncate those profile fields to a configurable length, default 20000 characters, and updates the acceptance test to test truncating the `staff` user's `goals` field.

Could you please re-run the jenkins-acceptance tests?  Also, I don't seem to have access to `jenkins-ci.analytics.edx.org`, so if there are further errors, could you please send them to me?  The module_engagement acceptance test is running successfully on my vagrant analyticstack.

Thank you!

**Comment by mulby** [comment]
Kicked off a validation with our prod data, as well as our acceptance test suite. I'll let you know if I see any other issues!

**Comment by pomegranited** [comment]
@mulby Looks like the acceptance tests failed again 😦 
Could you send me the report, or get me access to the jenkins instance, so I can address the issues?

Also, any issues with the prod validation?

**Comment by mulby** [comment]
@pomegranited - prod validation passed, acceptance tests failed due to an unrelated infrastructure issue.

This is ready to merge!

**Comment by pomegranited** [comment]
@mulby OMG REALLY??  I'm doing it now before I have to rebase again!  😄

**Comment by brianhw** [comment]
Congrats!

**Comment by pomegranited** [comment]
@brianhw @mulby Thank you so much for your help from design through implementation!  I'd love to see more of the analytics data made accessible from ElasticSearch/Analytics API.

**Pull request merged**
