### PR TITLE
Produce a CSV in the specified output format

### PR DESCRIPTION
**Pull request by mulby**
@brianhw @jab5569

### CODE REVIEW

**Comment by brianhw** [comment]
This looks fine.  However, the transaction_*_per_item values are what should be used in the report, I assume, not the values from the original transaction.  So there will be some post-merge work to combine the two pull requests.

**Comment by mulby** [comment]
I've rebased this onto the head of financial-reporting

**Comment by mulby** [comment]
@brianhw @jab5569

**Comment by brianhw** [comment]
LGTM. :+1:

**Pull request merged**
