### PR TITLE
Add support for loading segment events.

### PR DESCRIPTION
**Pull request by brianhw**
* Add PruneEventPartitionsInVertica task.
* Acceptance test for loaded events into Vertica, using tracking log and segment log data.
* Add segment-logs override for acceptance.
* Move SchemaManagementTask to common.
* Add workflow entry point.

Note that non-ascii characters in input log files seem to break template substitition in event files.

### CODE REVIEW

**Comment by tobz** [comment]
So this intends to shove all tracking log and all Segment events into the same table in Vertica, and that table would be partitioned?

**Comment by brianhw** [comment]
@tobz  Actually, it intends to merge the code that we've been running since August into master.  But yes, that code shoves all tracking log and segment log events into a single table.  This PR also adds the partitioning by day, and enforcing an optional retention policy also by day.

**Comment by brianhw** [comment]
I removed the segment_event_type_dist, since it's not actually in production.  That improved the codecov/project coverage.  But because I moved code that's not under unit test, I got hit with the codecov/patch failure.

**Comment by brianhw** [comment]
I also added pep8 fixes and the ansible fix.

**Review by tobz — APPROVED** [review]
LGTM.  I'm totally not worried about the coverage failure for the PR itself.

**Comment by brianhw** [comment]
Oh, and acceptance tests ran cleanly last night.

**Comment by brianhw** [comment]
Event exports have used this since Friday, but without pruning enabled for now.

**Review by mulby — APPROVED** [review]
LGTM

**Pull request merged**
