### PR TITLE
Fix warehouse loading tasks

### PR DESCRIPTION
**Pull request by HassanJaveed84**
These two tasks stopped working after the latest release(reminder to myself to run complete acceptance test suite before merging..)

### CODE REVIEW

**Review by brianhw — APPROVED** [review]
Code change looks good.   I'm assuming that there is no testing that needs to change for this, since the acceptance tests are currently passing.

**Comment by HassanJaveed84** [comment]
I'm going to double check by running acceptance test for these two tasks, load_warehouse job completed, so the acceptance tests should pass as well.

**Comment by brianhw** [comment]
I confirmed that test_internal_reporting_user acceptance test that currently fails in master runs successfully on this branch.

**Comment by HassanJaveed84** [comment]
Thanks Brian!

**Pull request merged**
