### PR TITLE
SE-1069 Module Engagement: handle case when no elasticsearch host is configured 

### PR DESCRIPTION
**Pull request by samuelallan72**
Runs just ModuleEngagementRosterPartitionTask instead of the full ModuleEngagementRosterIndexTask if no elasticsearch host is configured.

**JIRA tickets**: [OSPR-3784](https://openedx.atlassian.net/browse/OSPR-3784)

**Discussions**: https://github.com/open-craft/edx-analytics-pipeline/pull/10

**Dependencies**: None

**Merge deadline**: None

**Testing instructions**:

1. don't configure an elasticsearch host (TODO: full instructions)
2. verify that ModuleEngagementRosterPartitionTask shows in the ModuleEngagementWorkflowTask task logs, instead of ModuleEngagementRosterIndexTask

**Author notes and concerns**:

**Reviewers**
- [x] @pomegranited 
- [ ] edX reviewer[s] TBD

**Settings**
```yaml

```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @swalladge! I've created [OSPR-3784](https://openedx.atlassian.net/browse/OSPR-3784) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@swalladge Thank you for your contribution. Please let me know once it is ready for our review.

**Review by pomegranited — APPROVED** [review]
@swalladge  :+1:  

In the process of getting the acceptance tests working, I discovered [a bug](https://github.com/edx/edx-analytics-pipeline/pull/751/commits/1c16d6fff71222a07738b1b4f5175e8f640998e2#diff-883b68b39f9e5cec7cb38c694c38fdf1R1452) in original commit from the client's branch, so we'll need to make sure this fix makes it there too.

- [x] I tested this by verifying that this code runs as expected on our client's instance, which does not have `[elasticsearch] host` configured.
   Also ran the updated acceptance tests from this branch:
   1. Set up the [Analytics Pipeline docker devstack](https://github.com/edx/devstack#getting-started-on-analytics)
   1. Check out this branch and install it:
      ```
      make analytics-pipeline-shell
      # From devstack/Makefile#L300
      sudo chown -R hadoop:hadoop /edx/app/analytics_pipeline
      source /edx/app/hadoop/.bashrc
      make install
      ```
   1. From the [analytics-pipeline-shell](https://github.com/edx/devstack/blob/99920e12d18ef3cab6cc583c7b13fd823f50424b/Makefile#L265-L266), ran:
      ```
      make develop-local
      make docker-test-acceptance-local ONLY_TESTS=edx.analytics.tasks.tests.acceptance.test_module_engagement
      ```
- [x] I checked the code against the client's branch https://github.com/edx/edx-analytics-pipeline/commit/ff19850b69714ca4c81e4aedc89646a132af74f0
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] Includes documentation: `ModuleEngagementWorkflowTask.host` field description provided, tasks are automatically documented from parameters.

**Comment by pomegranited** [comment]
This is ready for edX review, @natabene 

Uncertain what to do about the unit test coverage drop -- the only way I can think to unit test this basically mimics the code change itself.  But we've added an acceptance test which verifies the config change is ok, so hopefully that is enough?

**Comment by natabene** [comment]
@edx/analytics Please review this when you have a chance.

**Comment by openedx-webhooks** [comment]
@swalladge 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-pipeline&entry.867055334=https://github.com/edx/edx-analytics-pipeline/pull/751&entry.1484655318=https://github.com/swalladge&entry.752974735=2019-08-08+07:36&entry.1917517419=2019-08-14+16:31&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by brianhw** [comment]
I think the unit test coverage drop is small enough to not be worth worrying about.

**Comment by pomegranited** [comment]
Thank you @brianhw !

**Pull request merged**
