### PR TITLE
Handle null-duration video events.

### PR DESCRIPTION
**Pull request by brianhw**
Some video events have {"duration": null} entries.  These are now mapped to the default value used when duration is not specified.

### CODE REVIEW

**Review by HassanJaveed84 — APPROVED** [review]
LGTM 👍

**Review by muhammad-ammar — APPROVED** [review]
@brianhw This is looking good. Thanks for taking care of this. But now I am worried why duration is not set for some videos. This should not happen as video component always have the duration. I will look into this.

**Comment by muhammad-ammar** [comment]
@brianhw code coverage job is failing, I think you might need to add a unit test for the new code.

**Comment by brianhw** [comment]
After finally getting the video history copied from prod to dev, I was able to successfully run the release candidate on this branch.

**Pull request merged**
