### PR TITLE
rename tables course_enrollment_* -> course_enrollment_*_daily

### PR DESCRIPTION
**Pull request by jbau**
@mulby

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jbau! I've created [OSPR-147](https://openedx.atlassian.net/browse/OSPR-147) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. Supporting information that is good to add there is anything that can help Product understand the context for the PR - supporting documentation, edx-code email threads, timeline information ('this must be merged by XX date', and why that is), partner information (this is for a course on edx.org, for example), etc. 

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx.readthedocs.org/projects/userdocs/en/latest/process/overview.html).

**Comment by jbau** [comment]
acceptance tests running at http://jenkins-ci.analytics.edx.org/view/ad-hoc/job/edx-analytics-pipeline-acceptance-test-manual/106/

**Comment by mulby** [comment]
heh, beat me to it... thanks!

:+1:

**Comment by brianhw** [comment]
LGTM too. :+1:

**Comment by jbau** [comment]
acceptance tests passed, merging.

**Pull request merged**
