### PR TITLE
Upgrade numpy to it's latest version

### PR DESCRIPTION
**Pull request by muzaffaryousaf**
We need to upgrade this to keep the numpy versions in-sync across different repos. 
Platform PR: https://github.com/edx/edx-platform/pull/12444

### CODE REVIEW

**Comment by muzaffaryousaf** [comment]
@andy-armstrong @nedbat Different version in this repo would't complaint about VersionConflict, Do you think we should update the numpy version here ?

**Comment by andy-armstrong** [comment]
@muzaffaryousaf I'd check with @mulby as I'm not familiar with this repo.

**Comment by mulby** [comment]
This repo is installed in a separate virtualenv from edx-platform, so I would be surprised if you need to update this.

**Comment by muzaffaryousaf** [comment]
@mulby I've just updated this because it was using the older version, no other reason. I realized it later that we're not using it in edx-platform.

**Pull request closed without merging**
