### PR TITLE
WIP: ENT-880 Add course key to enterprise enrollment task

### PR DESCRIPTION
**Pull request by mattdrayer**
@georgebabey here's the analytics task to add the course key field to the necessary vertica table.

### CODE REVIEW

**Comment by brianhw** [comment]
LGTM.   Two small comments.   First, this is not currently for a Vertica table, but rather for a Mysql table.    Second, you may find that you need to drop the table before running the job.  We don't have migrations.  I *think* that it's enough to run the job with --overwrite-mysql, but I'm not sure if that deletes the table (and recreates it) or if it merely removes its contents before reloading.

**Comment by brianhw** [comment]
Yes, --overwrite-mysql only does a DELETE FROM table_name, not a DROP TABLE/CREATE TABLE.

**Review by georgebabey — APPROVED** [review]
This looks good to me, but I'm not terribly familiar with the pipeline side of the analytics-api. @brittneyexline is our resident expert, she have more insight (see what i did there..) into the needed changes

**Comment by mattdrayer** [comment]
@brittneyexline thoughts?

**Review by brittneyexline — APPROVED** [review]
looks good to me!

**Comment by mattdrayer** [comment]
Thanks!  Merging now 😄

**Pull request merged**
