### PR TITLE
Partial incrementalization of AnswerDistribution via Hive

### PR DESCRIPTION
**Pull request by tobz**
This is a redux of Brian's work, and then Alex's work, on working towards making AnswerDistribution incremental, by partially achieving incremental-ness by generating Hive partitions for each day's data.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @tobz! I've created [OSPR-2122](https://openedx.atlassian.net/browse/OSPR-2122) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by tobz** [comment]
Silly bot!  Also.. hi! 👋

**Comment by azafty468** [comment]
Ha, label changes result in re-triggering builds.  Also hi! 👋

**Comment by edx-webhook** [comment]
Thanks for the pull request, @tobz! I've created [OSPR-2359](https://openedx.atlassian.net/browse/OSPR-2359) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by mduboseedx** [comment]
@edx/analytics Is this PR still worth pursuing?

**Comment by brianhw** [comment]
This should not be an OSPR, and I'm not quite sure how it turned into one.
 This was a background project, and Toby was the last person working on
this when he was here.   It is on the back burner again while we work on
higher priority stories.  It probably has some context in its reviews that
might be useful, but those would still persist even if I closed it.

But in general, I would be curious to know what we should do in future to
prevent a long-running PR created by someone that then leaves the
organization from becoming an OSPR.

**Comment by mduboseedx** [comment]
@brianhw We have OPEN-2111 to have work done on the bot to prevent former employee PRs from triggering an OSPR. I've deleted the OSPR and will leave his PR open.

**Pull request closed without merging**
