### PR TITLE
Revert "Properly escape the names of Hive columns"

### PR DESCRIPTION
**Pull request by mulby**
Reverts edx/edx-analytics-pipeline#127

Not sure why it looks like acceptance tests were passing, but they aren't, reverting for now.

### CODE REVIEW

**Comment by mulby** [comment]
@brianhw 

@bradenmacdonald FYI - we have to revisit this, I am seeing this error message from Hive while running the acceptance tests (specifically the enrollment tests):

```
SemanticException [Error 10214]: Invalid partition spec specified dt not found in table's partition spec: {`dt`=2014-08-06}
```

**Comment by bradenmacdonald** [comment]
@mulby Rats. I was worried about something like this but didn't hit any errors in my own testing. Do you have a little more context for this error message to help me debug it? It could be that the syntax I used is not as backward compatible as I thought, or it could be a case of applying escaping twice or in the wrong context. I haven't yet been able to run the acceptance tests myself so it's tricky for me to troubleshoot.

**Comment by mulby** [comment]
@bradenmacdonald - yeah, I understand this will be tricky to resolve without actually running the tests, it might make the most sense for me to just diagnose it over here.

This was the task that failed:

```
CourseEnrollmentTableTask(overwrite=False, source=('REDACTED',), expand_interval=2 days, 0:00:00, pattern=('.*tracking.log-(?P<date>\\d{8}).*\\.gz', '.*tracking.notalog-(?P<date>\\d{8}).*\\.gz'), warehouse_path=REDACTED, interval=2014-08-01-2014-08-06)
```

I think the create table statement is failing? Hive isn't giving me a lot of debug output here unfortunately...

**Comment by bradenmacdonald** [comment]
@mulby FYI, these changes for for compatibility with Hive 1.2.1. I also had to make [a change to luigi](https://github.com/spotify/luigi/commit/1de379b56c346754bd9dbc7e921211ca570219c7) - perhaps it requires that change as well?

If this is too much hassle, we can just use an older Hive version and not bother with these changes - especially now that your new analytics devstack configuration is in the works.

But if there is a simple fix that allows compatibility with the old and newer Hive versions, that would be great.

**Pull request merged**
