### PR TITLE
overwrite_n_days for tasks

### PR DESCRIPTION
**Pull request by javimudi**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @javimudi! I've created [OSPR-2144](https://openedx.atlassian.net/browse/OSPR-2144) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-analytics-pipeline/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by javimudi** [comment]
Related https://github.com/edx/edx-analytics-pipeline/issues/383

**Comment by nedbat** [comment]
@javimudi Thanks! We are still waiting for your contributor agreement.

**Comment by javimudi** [comment]
@nedbat I just sent over the scanned contributor agreement to legal AT edx.org

**Comment by nedbat** [comment]
Thanks, we've received your agreement.

**Comment by nedbat** [comment]
@edx/analytics Can you take a look?

**Comment by azafty468** [comment]
Hello @javimudi, it looks like you are trying to pass down some required parameters in enrollment.py.  Looking through the code a better approach might be to remove the CourseEnrollmentDownstreamMixin and CourseSummaryEnrollmentDownstreamMixin mixin's on the Partition and Table tasks as these mixins introduce required parameters that are not used.  I also suspect the CourseSummaryEnrollmentDownstreamMixin on CourseProgramMetadataDataTask can be changed to something simpler like LoadInternalReportingCourseCatalogMixin.  

The Exception raised when attempting to overwrite a MySQL table with an empty record set however is a safeguard that we need to keep in place.

**Comment by javimudi** [comment]
Hi @azafty468,

If `overwrite_n_days` is not required for some tasks, your proposal is definitely a better approach. I'll check the requirements and change the PR accordingly.

Ok, I need to deeply check the mysql overwriting thing, but the truth is that an emptiness table check for that specific scenario sounds like some improvement. I could work on that.

Thanks for your help and revision.

**Comment by brianhw** [comment]
I think the underlying problem that this was addressing has now been fixed in #488 , along the lines suggested by @azafty468 back in January.  But thanks for your work on this -- it definitely helped to get this bug finally fixed!

**Comment by openedx-webhooks** [comment]
@javimudi Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-analytics-pipeline&entry.867055334=https://github.com/edx/edx-analytics-pipeline/pull/471&entry.1484655318=https://github.com/javimudi&entry.752974735=2018-01-16+14:17&entry.1917517419=2018-03-22+14:57&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
