### PR TITLE
Fail the module engagement workflow if the enrollment data is missing

### PR DESCRIPTION
**Pull request by mulby**
Reviewers:
- [x] @brianhw 
- [x] @HassanJaveed84

### CODE REVIEW

**Comment by brianhw** [comment]
LGTM.  👍 

But it reminds me that we encode table names outside of tasks pretty freely, and it might be good at some point if there were some encapsulation.

**Comment by mulby** [comment]
Acceptance tests passed.

http://jenkins-ci.analytics.edx.org/view/ad-hoc/job/edx-analytics-pipeline-acceptance-test-manual/862/

**Comment by HassanJaveed84** [comment]
LGTM 👍 
Quick question, previously we specified CourseEnrollment as a dependency, and I think the Jenkins build  for module_engagement is triggered to run after the enrollments job. Out of curiosity would Jenkins schedule module engagement if enrollments build fails ?

**Comment by mulby** [comment]
Currently it will not schedule the module engagement build unless the enrollment job succeeds.

**Pull request merged**
