### PR TITLE
Removed redundant test.

### PR DESCRIPTION
**Pull request by HassanJaveed84**

### CODE REVIEW

**Comment by brianhw** [comment]
Are there includes that are no longer necessary?

**Comment by HassanJaveed84** [comment]
Great catch! 
Removed unused imports, I had always run make coverage-local to see any pending issues, but it doesn't show any violations for me anymore. Do we have that output captured in our CI ? I couldn't find any.

**Review by brianhw — APPROVED** [review]
LGTM.   👍

**Review by brianhw — CHANGES_REQUESTED** [review]
Hmm.   Actually, the Travis builds are failing: 

ERROR: /edx/app/analytics_pipeline/analytics_pipeline/edx/analytics/tasks/tests/acceptance/test_financial_reports.py Imports are incorrectly sorted.

**Comment by brianhw** [comment]
When I run isort on your branch locally, I get:
```
from edx.analytics.tasks.tests.acceptance import (
-    AcceptanceTestCase, coerce_columns_to_string, read_csv_fixture_as_list, when_vertica_available,
+    AcceptanceTestCase, coerce_columns_to_string, read_csv_fixture_as_list, when_vertica_available
 )
```

**Comment by HassanJaveed84** [comment]
Thanks, make coverage seems to be broken on my vagrant box, isort was erroring on all files. Fixed now.

**Review by brianhw — APPROVED** [review]

**Comment by brianhw** [comment]
I was not using Vagrant, but just running locally.

**Pull request merged**
